name: Make Version

on:
  workflow_dispatch: { }

permissions:
  contents: read


jobs:
  bump-version:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.bump-version.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0 # fetch all history, commits and tags, we scan it to the last tag and look at commits, we need all of it to determine the next version
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "24"
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@29979bc5339bf54f76a11ac36ff67701986bb0f0
        with:
          nodeVersion: "24"
      - name: Version
        id: bump-version
        run: |
          node lib/cli.js
          VERSION=$(cat package.json | jq .version -r)
          echo "Bumped version to $VERSION"
          echo "RELEASE_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Update version in lock file
        run: |
          VERSION=${{ steps.bump-version.outputs.RELEASE_VERSION }}
          # update the version in package-lock.json (in two places: once in the top-level and once in the dependencies)
          jq --arg version "$VERSION" '.version = $version | .packages."".version = $version' package-lock.json > package-lock.json.tmp && mv package-lock.json.tmp package-lock.json
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Stage changes
        run: git add .
      - name: Create PR
        id: create-pr
        uses: ./.github/actions/create-pr
        with:
          temp_branch_prefix: "ci-bump"
          pull_request_title: "chore: bump version to ${{ steps.bump-version.outputs.RELEASE_VERSION }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}